// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0KW_6ROERMISzs680nT0G9AfMduVHKpU',
    appId: '1:197398794626:web:999020187f2f4a77ac7f9b',
    messagingSenderId: '197398794626',
    projectId: 'chatapp-b4670',
    authDomain: 'chatapp-b4670.firebaseapp.com',
    storageBucket: 'chatapp-b4670.firebasestorage.app',
    measurementId: 'G-ZF51KC3WHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1MmkPnLebIZ75FZQL9VWe8o7sA-OL4x8',
    appId: '1:197398794626:android:1f0dc3ab6a27ad33ac7f9b',
    messagingSenderId: '197398794626',
    projectId: 'chatapp-b4670',
    storageBucket: 'chatapp-b4670.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDcV9MKJtwW-JrisEtey-1b-mNO2z1JJk',
    appId: '1:197398794626:ios:04444da043114412ac7f9b',
    messagingSenderId: '197398794626',
    projectId: 'chatapp-b4670',
    storageBucket: 'chatapp-b4670.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDcV9MKJtwW-JrisEtey-1b-mNO2z1JJk',
    appId: '1:197398794626:ios:04444da043114412ac7f9b',
    messagingSenderId: '197398794626',
    projectId: 'chatapp-b4670',
    storageBucket: 'chatapp-b4670.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0KW_6ROERMISzs680nT0G9AfMduVHKpU',
    appId: '1:197398794626:web:0abd672a995a8c4fac7f9b',
    messagingSenderId: '197398794626',
    projectId: 'chatapp-b4670',
    authDomain: 'chatapp-b4670.firebaseapp.com',
    storageBucket: 'chatapp-b4670.firebasestorage.app',
    measurementId: 'G-M5Y4KPRYPP',
  );
}
